-- Yearworm D1 schema. Apply with:
--   wrangler d1 execute yearworm --remote --file=schema.sql
CREATE TABLE IF NOT EXISTS scores (
  day     INTEGER NOT NULL,   -- daily number (#1 = 1 July 2026)
  device  TEXT    NOT NULL,   -- anonymous random token generated by the client
  nick    TEXT    NOT NULL,
  score   INTEGER NOT NULL,   -- 0..5
  time_ms INTEGER NOT NULL,   -- total thinking time (per-turn capped client-side)
  created INTEGER NOT NULL,   -- unix ms; breaks ties after score+time
  PRIMARY KEY (day, device)
);
CREATE INDEX IF NOT EXISTS idx_scores_day ON scores(day, score DESC, time_ms ASC);

-- challenge-set results: every finished run on a shared song set, keyed by the
-- set itself (pool indices joined with dots) — powers cross-device boards
CREATE TABLE IF NOT EXISTS chals (
  setkey  TEXT    NOT NULL,
  device  TEXT    NOT NULL,
  nick    TEXT    NOT NULL,
  score   INTEGER NOT NULL,
  time_ms INTEGER NOT NULL,
  created INTEGER NOT NULL,
  PRIMARY KEY (setkey, device)
);
CREATE INDEX IF NOT EXISTS idx_chals_set ON chals(setkey, score DESC, time_ms ASC);

-- social layer: a user is a claimed handle + a shareable friend code. A device
-- token (the same anonymous token the boards use) links to at most one user;
-- later real login (email/OAuth) attaches to users without touching this.
CREATE TABLE IF NOT EXISTS users (
  id        TEXT PRIMARY KEY,      -- random hex, server-generated
  handle    TEXT NOT NULL,         -- display name as typed
  handle_lc TEXT NOT NULL UNIQUE,  -- lowercased for uniqueness
  code      TEXT NOT NULL UNIQUE,  -- friend code, e.g. YW-7F3KQ2
  avatar    TEXT,                  -- profile picture id (e.g. m:12) or short emoji; NULL = default
  sbest     INTEGER,               -- survival best (standard decks only) — friends leaderboard
  tbest     INTEGER,               -- turbo best (standard decks only)
  created   INTEGER NOT NULL
);
-- migration for existing databases (safe to run once; errors if already added):
--   wrangler d1 execute yearworm --remote --command "ALTER TABLE users ADD COLUMN avatar TEXT"
CREATE TABLE IF NOT EXISTS devices (
  device  TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  created INTEGER NOT NULL
);
-- one row per pair; (a,b) is the sorted pair, requester says who asked
CREATE TABLE IF NOT EXISTS friends (
  a         TEXT NOT NULL,
  b         TEXT NOT NULL,
  requester TEXT NOT NULL,
  status    TEXT NOT NULL,         -- 'pending' | 'accepted'
  created   INTEGER NOT NULL,
  PRIMARY KEY (a, b)
);
-- direct messages of structured kinds (no free text): challenges for now
CREATE TABLE IF NOT EXISTS inbox (
  id        INTEGER PRIMARY KEY AUTOINCREMENT,
  to_user   TEXT NOT NULL,
  from_user TEXT NOT NULL,
  kind      TEXT NOT NULL,         -- 'challenge'
  payload   TEXT NOT NULL,         -- JSON: {set, score, timeMs}
  created   INTEGER NOT NULL,
  seen      INTEGER NOT NULL DEFAULT 0,
  shown     INTEGER NOT NULL DEFAULT 0   -- first delivered to the app; FYI rows auto-clear 3 days after this
);
CREATE INDEX IF NOT EXISTS idx_inbox_to ON inbox(to_user, seen, created DESC);

-- "this clip has no singing": the one defect the version picker cannot see,
-- because it reads track/album text and the problem is in the audio. One vote
-- per device; the track retires itself once CLIP_FLAG_RETIRE devices agree.
CREATE TABLE IF NOT EXISTS clip_flags (
  track_id  INTEGER NOT NULL,
  device    TEXT NOT NULL,
  at        INTEGER NOT NULL,
  PRIMARY KEY (track_id, device)
);

-- head-to-head duel results: one row per answered inbox challenge (msg_id
-- dedupes — the first reported result stands). Powers the friends leaderboard.
CREATE TABLE IF NOT EXISTS duels (
  id      INTEGER PRIMARY KEY AUTOINCREMENT,
  msg_id  INTEGER NOT NULL UNIQUE,  -- the inbox challenge this answers
  a       TEXT NOT NULL,            -- challenger
  b       TEXT NOT NULL,            -- opponent (who reported the result)
  score_a INTEGER, score_b INTEGER,
  time_a  INTEGER, time_b  INTEGER,
  winner  TEXT NOT NULL,            -- user id of the winner, '' for a tie
  created INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_duels_a ON duels(a);
CREATE INDEX IF NOT EXISTS idx_duels_b ON duels(b);

-- friends is queried "WHERE a=? OR b=?" (PK covers a)
CREATE INDEX IF NOT EXISTS idx_friends_b ON friends(b);

-- external logins attached to a user (Google for now). A login is how the
-- same account comes back on a new phone; a user can exist without one.
CREATE TABLE IF NOT EXISTS logins (
  provider TEXT NOT NULL,          -- 'google'
  subject  TEXT NOT NULL,          -- provider's stable user id (Google sub)
  user_id  TEXT NOT NULL,
  email    TEXT,                   -- optional, for support/recovery only
  created  INTEGER NOT NULL,
  PRIMARY KEY (provider, subject)
);
-- the index must come AFTER the table: IF NOT EXISTS guards the index itself,
-- not a missing table, so declaring it earlier breaks a fresh-database install
CREATE INDEX IF NOT EXISTS idx_logins_user ON logins(user_id);

-- Web Push subscriptions: one row per device endpoint a user opted in from.
CREATE TABLE IF NOT EXISTS push_subs (
  endpoint TEXT PRIMARY KEY,       -- the push service URL (unique per device)
  user_id  TEXT NOT NULL,
  p256dh   TEXT NOT NULL,          -- subscription public key (b64url)
  auth     TEXT NOT NULL,          -- subscription auth secret (b64url)
  created  INTEGER NOT NULL,
  tz       INTEGER,                -- minutes east of UTC (evening streak nudge)
  nudged   INTEGER                 -- last daily number a streak nudge was sent for
);
-- NB: on an EXISTING database the tz/nudged columns arrive via the scheduled
-- handler's lazy ALTERs (worker.js) — this file only shapes fresh installs.
CREATE INDEX IF NOT EXISTS idx_push_user ON push_subs(user_id);

-- per-day survival scores → daily & rolling-7-day friend leaderboards.
-- (On an existing DB this table is created lazily in the scheduled() handler.)
CREATE TABLE IF NOT EXISTS sscores (
  day     INTEGER,
  user_id TEXT,
  score   INTEGER,
  created INTEGER
);
CREATE INDEX IF NOT EXISTS idx_sscores ON sscores (user_id, day);

-- who created a shared challenge set (first submitter), so we can notify them
-- when someone else plays it.
CREATE TABLE IF NOT EXISTS chal_owner (
  setkey  TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  created INTEGER NOT NULL
);

-- Shared iTunes lookup cache. Apple rate-limits per CLIENT IP, and iCloud
-- Private Relay / carrier CGNAT put thousands of phones behind one, so players
-- get blocked before their first lookup. Going through the Worker means Apple
-- sees one IP AND every answer is reused: the daily's five songs cost five
-- lookups worldwide per TTL instead of five per player.
CREATE TABLE IF NOT EXISTS previews (
  term TEXT PRIMARY KEY,
  json TEXT NOT NULL,
  at   INTEGER NOT NULL
);

-- Which Apple track a search term resolves to. The SERVER picks the version
-- (never the client: anything a phone posts can be forged, and five app
-- versions would each pick differently), and pins it so every player from then
-- on hears the identical recording. No TTL — a pin stands until proven dead.
CREATE TABLE IF NOT EXISTS pins (
  term     TEXT PRIMARY KEY,
  track_id INTEGER NOT NULL,
  at       INTEGER NOT NULL
);

-- Tracks Apple no longer serves a preview for. Without this the re-search after
-- a dead pin would keep choosing the same dead track and re-pinning it — not a
-- spin on one device, but a fresh failure for every player, forever.
CREATE TABLE IF NOT EXISTS dead_ids (
  track_id INTEGER PRIMARY KEY,
  at       INTEGER NOT NULL
);

-- Funnel counters: how many people who LAND actually start a round, and how
-- many finish one. Counts only — no device token, no session id, nothing that
-- identifies anyone. Without this, a marketing push tells you "3 of 100 stayed"
-- and you cannot tell a boring game from a leaking funnel.
CREATE TABLE IF NOT EXISTS funnel (
  day  INTEGER NOT NULL,
  step TEXT NOT NULL,
  n    INTEGER NOT NULL,
  PRIMARY KEY (day, step)
);

-- migrations for existing databases (run once each; harmless "duplicate"/"exists" errors are fine):
--   wrangler d1 execute yearworm --remote --command "ALTER TABLE users ADD COLUMN avatar TEXT"
--   wrangler d1 execute yearworm --remote --command "CREATE TABLE IF NOT EXISTS push_subs (endpoint TEXT PRIMARY KEY, user_id TEXT NOT NULL, p256dh TEXT NOT NULL, auth TEXT NOT NULL, created INTEGER NOT NULL)"
--   wrangler d1 execute yearworm --remote --command "CREATE TABLE IF NOT EXISTS chal_owner (setkey TEXT PRIMARY KEY, user_id TEXT NOT NULL, created INTEGER NOT NULL)"
